version: "3"

services:
  forum-postgres:
    image: postgres:12.3
    container_name: "my_postgres"
    ports:
      - "5432:5432"
    volumes:
      -   postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: oneboss
      POSTGRES_DB: forum
      POSTGRES_PASSWORD: boss

volumes:
  postgres-data: